# Reference: http://docs.travis-ci.com/user/languages/perl/
language: perl
perl:
  - "5.22"

sudo: false

addons:
  apt:
    packages:
    - curl 
    - rsync 
    - tar 
    - make 
    - perl 
    - perl-base 
    - build-essential 
    - libncurses-dev 
    - libexpat1-dev 
    - libssl-dev 
    - libmysqlclient-dev 
    - libxml2-dev
    - tabix
    - samtools 

env:
  - VEP_PATH=$HOME/vep VEP_DATA=$HOME/.vep VER=93 PERL5LIB=$VEP_PATH:$PERL5LIB PATH=$VEP_PATH/htslib:$PATH

before_install:
  ## - sudo apt-get install -y curl rsync tar make perl perl-base build-essential libncurses-dev libexpat1-dev libssl-dev libmysqlclient-dev libxml2-dev
  - cpanm --notest JSON JSON::Parse XML::Parser XML::Simple LWP LWP::Simple LWP::Protocol::https Archive::Extract Archive::Tar Archive::Zip CGI DBI Time::HiRes DBD::mysql Bio::Perl

install:
  ## - sudo apt-get install tabix
  ## install samtools
  ## we should be able to do this via apt-get
  ## - wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
  ## - tar -vxjf samtools-1.9.tar.bz2
  ## - cd samtools-1.9
  ## - make
  ## - make install;  later try setting the installation path via `/home/travis/`
  - cd ..
  - git clone https://github.com/aparton/ensembl-vep.git
  - cd ensembl-vep
  - perl INSTALL.pl --AUTO acf --SPECIES saccharomyces_cerevisiae --ASSEMBLY R64-1-1 --CACHEDIR $VEP_DATA
  - pwd
  - cd ..
  - pwd
  ## - perl INSTALL.pl --AUTO acf --SPECIES homo_sapiens --ASSEMBLY GRCh37 --CACHEDIR $VEP_DATA

script:
  - perl vcf2maf.pl --input-vcf tests/test.vcf --output-maf tests/test.vep.maf --custom-enst data/isoform_overrides_at_mskcc --vep-forks 1